language: node_js
node_js:
  - "10.16.3"

install:
  - npm install

script:
  - npm run build

after_success:
  - cd ./dist
  - git init
  - git add .
  - git commit -m "deploy"
  - git push --quiet --force "https://${GITHUB_TOKEN}@${GH_REF}" master:${P_BRANCH}

branches:
  only:
    - master