language: node_js
node_js:
  - "10.16.3"

cache: npm

script:
  - npm install
  - npm run build

deploy:
provider: pages
skip_cleanup: true
github_token: $GITHUB_TOKEN
local_dir: dist
on:
  branch: master